### ISSUE TITLE
Iteration reset necessary

### ISSUE THREAD

**Issue by BerelexQ** [alice-st/DARP#12]
Olivier here,

You will want to add an "iteration =0" at this spot, in order for the subsequent loops (when self.MaxIter gets divided by 2) to actually take place, and not simply to be skipped.
https://github.com/alice-st/DARP/blob/c2d90a565709daadc335f3cfaac9cffc7e5f1a48/darp.py#L224

**Comment by alice-st** [comment]
Corrected in pull request.
