### ISSUE TITLE
How to get all possible path

### ISSUE THREAD

**Issue by raymond2338** [alice-st/DARP#15]
How can i get all possible path (or all possible MST generated)?

**Comment by alice-st** [comment]
All possible paths are saved in  AllRealPaths_dict, in MultiRobotPathPlanner class. This dict contains all available paths for each mode, for each drone (AllRealPaths_dict[mode][drone]). So, for example, if you want to get the first drone's path, using mode 1, you can type AllRealPaths_dict[1][0]. AllRealPaths_dict is not currently an attribute of the MultiRobotPathPlanner class, but you can easily make it by adding a self. in front of it.

**Comment by raymond2338** [comment]
as a follow up question, it looks like there are at max four possible path listed (ie mode)? Imagine a 8x8 grid (with no obstacles), there should be more than 4 different spanning tree which implies there should be more than 4 paths? In that case, is that computed in this code as well?

**Comment by alice-st** [comment]
Indeed, you are right! There are multiple spanning trees for a given graph of the same weights. However, this has nothing to do with our implementation. The four different modes are formed by giving different weights on the nodes’ connections (Kruskal.py lines 23-30). These four different modes denote just the way that the spanning tree is going to be connected at the end. Given that we consider that a node can only be connected with 4 adjacent nodes, there is no other option in our approach.
