### ISSUE TITLE
Dependencies don't match

### ISSUE THREAD

**Issue by berendjan10** [alice-st/DARP#17]
When installing venv using instructions, I get the error message:

`ERROR: No matching distribution found for numba==0.54.1
`
I'removed version specification for numba. Then:

```
The conflict is caused by:
    The user requested numpy==1.20
    opencv-python 4.5.4.60 depends on numpy>=1.21.2
```

I removed version specification for numpy. Now it works.

So, installation is successful when you change Dependencies.sh into:
```
if [ "$#" -ne 1 ]; then
  echo "Give only one argument, the name of the virtual environment to create"
  exit
fi

python3 -m venv $1

source $1/bin/activate

pip install \
	numpy\
	opencv-python==4.5.4.60 \
	pygame==2.1.0 \
	scipy==1.7.3 \
	jupyter==1.0.0 \
  numba\
  nose==1.3.7\
  parameterized==0.8.1\
  sklearn \
  Pillow
```

I'm on Ubuntu 22.04 LTS

**Comment by alice-st** [comment]
Hello! Can you please specify the Python version you used when this issue occurred?

**Comment by alice-st** [comment]
Closed.
