### ISSUE TITLE
self.BWlist matrix generation inside assign methode is probably useless?

### ISSUE THREAD

**Issue by 0x000eHx** [alice-st/DARP#8]
Hey there, while browsing through the code and inserting my own runtime improvements I realized the `self.BWlist` matrix inside the `assign` methode (with numba njit now a function) will always get generated but never used in the main update loop.
At the end of the update loops the `self.getBinaryRobotRegions()` methode generates the `self.BinaryRobotRegions` matrix, which will be used for the pathfinding later... so you get the robot segments (in a binary way) in a n-dimensional array there.
The BWList generation is useless in my point of view, cause the algorithm never uses the in-between-steps for anything.
You could remove `self.BWlist` or do you have reasons to keep it?

Have a nice day :)

**Comment by alice-st** [comment]
Good morning! You are absolutely right, we do not need this matrix after all. Would you like to do a pull request?

Thank you!

**Comment by 0x000eHx** [comment]
sure

**Comment by 0x000eHx** [comment]
#9

**Comment by 0x000eHx** [comment]
#9
